
"use client";

import * as React from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Loader2, Sparkles, Save, Pencil } from "lucide-react"; // Import Pencil icon

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { useToast } from "@/hooks/use-toast";
import type { Persona } from "@/types/persona";
// Note: Reusing createPersonaAction logic for simplicity. In a real app, you might have a dedicated update action.
import { createPersonaAction, type CreatePersonaInput } from "@/app/actions";


const formSchema = z.object({
  name: z.string().min(2, { message: "Name must be at least 2 characters." }).max(50),
  description: z.string().min(10, {
    message: "Description must be at least 10 characters.",
  }).max(500, {
    message: "Description cannot exceed 500 characters.",
  }),
  isDreamScenario: z.boolean().default(false).optional(),
  // Note: greeting, tone, skills are generated by the AI, so we don't edit them directly here.
  // The AI will regenerate them based on the updated name/description.
});

type PersonaEditDialogProps = {
  isOpen: boolean;
  onClose: () => void;
  persona: Persona;
  onPersonaUpdated: (persona: Persona) => void;
};

export function PersonaEditDialog({ isOpen, onClose, persona, onPersonaUpdated }: PersonaEditDialogProps) {
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = React.useState(false);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    // Initialize form with existing persona data
    defaultValues: {
      name: persona.name,
      description: persona.description,
      isDreamScenario: persona.isDreamScenario ?? false,
    },
  });

   // Reset form when the persona prop changes (e.g., when opening dialog for a different persona)
    React.useEffect(() => {
        if (persona) {
        form.reset({
            name: persona.name,
            description: persona.description,
            isDreamScenario: persona.isDreamScenario ?? false,
        });
        }
    }, [persona, form]);


  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsSubmitting(true);
    try {
        // Use the createPersona action again to regenerate details based on updated description/name
        const actionInput: CreatePersonaInput = {
            personaDescription: values.description,
            isDreamScenario: values.isDreamScenario
        };
        // We use the *new* description to regenerate AI fields, but keep the user's chosen name
        const regeneratedDetails = await createPersonaAction(actionInput);

      const updatedPersona: Persona = {
        ...persona, // Keep original ID, createdAt, isPublished, etc.
        name: values.name, // Use the user-edited name
        description: values.description, // Use the user-edited description
        // Use regenerated details from AI
        greeting: regeneratedDetails.personaGreeting,
        tone: regeneratedDetails.personaTone,
        skills: regeneratedDetails.personaSkills,
        isDreamScenario: values.isDreamScenario,
      };

      onPersonaUpdated(updatedPersona);
      toast({
        title: "Persona Updated!",
        description: `${updatedPersona.name} has been successfully updated.`,
      });
      onClose(); // Close the dialog on success
    } catch (error) {
      console.error("Failed to update persona/scenario:", error);
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Could not update. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-[525px] bg-card/95 backdrop-blur-sm">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Pencil size={20} /> Edit Persona: {persona.name}
          </DialogTitle>
          <DialogDescription>
            Modify the details below. The AI will regenerate greeting, tone, and skills based on the new description.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6 py-4">
             <FormField
                control={form.control}
                name="name"
                render={({ field }) => (
                    <FormItem>
                    <FormLabel>Persona Name</FormLabel>
                    <FormControl>
                        <Input
                        placeholder="Enter a unique name"
                        className="transition-shadow duration-200 focus:shadow-md bg-background/80"
                        {...field}
                        disabled={isSubmitting}
                        />
                    </FormControl>
                    <FormMessage />
                    </FormItem>
                )}
                />

            <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Persona Description / Scenario</FormLabel>
                    <FormControl>
                    <Textarea
                        placeholder="Describe the AI persona OR the Dream Scenario..."
                        className="resize-none transition-shadow duration-200 focus:shadow-md bg-background/80"
                        {...field}
                        disabled={isSubmitting}
                        rows={5} // Slightly more rows for editing
                    />
                    </FormControl>
                    <FormDescription>
                    Updating this will regenerate the AI's greeting, tone, and skills.
                    </FormDescription>
                    <FormMessage />
                </FormItem>
                )}
            />

            <FormField
                control={form.control}
                name="isDreamScenario"
                render={({ field }) => (
                <FormItem className="flex flex-row items-start space-x-3 space-y-0 rounded-lg border border-border/50 p-4 shadow-sm hover:shadow-md transition-shadow duration-200 bg-card/80 backdrop-blur-sm">
                <FormControl>
                    <Checkbox
                    checked={field.value}
                    onCheckedChange={field.onChange}
                    disabled={isSubmitting}
                    className="transition-colors duration-200 mt-1"
                    />
                </FormControl>
                <div className="space-y-1 leading-none">
                    <FormLabel className="flex items-center gap-1.5 font-semibold">
                        <Sparkles size={16} className="text-secondary"/> Dream Scenario Mode
                    </FormLabel>
                    <FormDescription>
                    Simulates a chatroom with multiple characters.
                    </FormDescription>
                </div>
                </FormItem>
            )}
            />

            <DialogFooter>
                <DialogClose asChild>
                 <Button type="button" variant="outline" disabled={isSubmitting}>
                    Cancel
                 </Button>
                </DialogClose>
                <Button type="submit" disabled={isSubmitting} className="button-fancy">
                {isSubmitting ? (
                    <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Saving...
                    </>
                ) : (
                    <>
                     <Save className="mr-2 h-4 w-4" />
                     Save Changes
                    </>
                )}
                </Button>
            </DialogFooter>
            </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}

